export default {
  INDICO_ANALYZE_REQUEST: "INDICO_ANALYZE_REQUEST",
  INDICO_ANALYZE_SUCCESS: "INDICO_ANALYZE_SUCCESS",
  INDICO_ANALYZE_ERROR: "INDICO_ANALYZE_ERROR",

  SET_WALLS_COLOR: "SET_WALLS_COLOR",
  SET_RUG_COLOR: "SET_RUG_COLOR",
  SET_WINDOW_COLOR: "SET_WINDOW_COLOR",
  SET_DRESSER_COLOR: "SET_DRESSER_COLOR",
  SET_TABLE_COLOR: "SET_TABLE_COLOR",
  SET_DECORATIONS_COLOR: "SET_DECORATIONS_COLOR",
  SET_BED_COLOR: "SET_BED_COLOR",

  INCREMENT_CURRENT_QUESTION: "INCREMENT_CURRENT_QUESTION",
  INCREMENT_CURRENT_SECTION: "INCREMENT_CURRENT_SECTION"
};
